str="mycaptain is the best"
x=str.capitalize()
print (x)
y=str.upper()
print(y)
z=y.lower()
print(z)
print(y.count("BEST"))
print(x.find("t"))
print(x.index("is"))
print(x.isupper())
print(y.isupper())
print(str.replace("best","finest"))
print(str.rfind("p"))
print(str.rindex("my"))
print(x.rsplit(" "))
print(str.title())
print(x.swapcase())
